<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class SadarinTagSeeder extends Seeder
{
    public function run(): void
    {
        $tags = [
            /*
            |--------------------------------------------------------------------------
            | SUBAG UMUM DAN KEPEGAWAIAN
            |--------------------------------------------------------------------------
            */

            'Kepegawaian',
            'Data Pegawai',
            'Administrasi Kepegawaian',
            'Kepegawaian ASN',
            'PNS',
            'PPPK',
            'PJLP',
            'Tenaga Kontrak',
            'Daftar Urut Kepangkatan',
            'DUK',
            'Kenaikan Pangkat',
            'Kenaikan Gaji Berkala',
            'KGB',
            'Mutasi Pegawai',
            'Rotasi Pegawai',
            'Promosi Pegawai',
            'Pelantikan Pegawai',
            'Pengangkatan Pegawai',
            'Pemberhentian Pegawai',
            'Pensiun Pegawai',
            'Cuti Pegawai',
            'Cuti Tahunan',
            'Cuti Sakit',
            'Cuti Melahirkan',
            'Cuti Besar',
            'Cuti Alasan Penting',
            'Izin Pegawai',
            'Absensi Pegawai',
            'Kehadiran Pegawai',
            'Disiplin Pegawai',
            'Sasaran Kinerja Pegawai',
            'SKP',
            'Evaluasi Kinerja Pegawai',
            'Penilaian Kinerja',
            'Pengembangan Kompetensi',
            'Diklat Pegawai',
            'Pelatihan Pegawai',
            'Seminar Pegawai',
            'Workshop Pegawai',
            'Sertifikasi Pegawai',
            'Pengembangan SDM',
            'Jabatan',
            'Jabatan Fungsional',
            'Jabatan Pelaksana',
            'Jabatan Struktural',
            'Pangkat dan Golongan',
            'Eselon',
            'Pendidikan Pegawai',
            'Profil Pegawai',
            'Kartu Pegawai',
            'Kartu Istri',
            'Kartu Suami',
            'Data NIP',
            'Data NIK',
            'Data Keluarga Pegawai',
            'Administrasi Umum',
            'Surat Masuk',
            'Surat Keluar',
            'Disposisi',
            'Naskah Dinas',
            'Nota Dinas',
            'Surat Tugas',
            'Surat Perintah',
            'Surat Edaran',
            'Surat Undangan',
            'Surat Keterangan',
            'Surat Pengantar',
            'Arsip Surat',
            'Tata Persuratan',
            'Kearsipan',
            'Arsip Internal',
            'Administrasi Perkantoran',
            'Rumah Tangga Kantor',
            'Pemeliharaan Gedung',
            'Pemeliharaan Kantor',
            'Kebersihan Kantor',
            'Keamanan Kantor',
            'Fasilitas Kantor',
            'Sarana Prasarana',
            'Inventaris Kantor',
            'Barang Milik Daerah',
            'BMD',
            'Aset Daerah',
            'Pengadaan Barang',
            'Pengadaan Jasa',
            'Pemeliharaan Aset',
            'Serah Terima Barang',
            'Berita Acara',
            'Notulen Rapat',
            'Rapat Internal',
            'Dokumentasi Internal',

            /*
            |--------------------------------------------------------------------------
            | PPEP
            |--------------------------------------------------------------------------
            */

            'Perencanaan',
            'Perencanaan Program',
            'Perencanaan Kegiatan',
            'Perencanaan Anggaran',
            'Perencanaan Tahunan',
            'Perencanaan Strategis',
            'Renstra',
            'Renja',
            'Rencana Kerja',
            'Rencana Aksi',
            'Indikator Kinerja',
            'Indikator Program',
            'Indikator Kegiatan',
            'Target Kinerja',
            'Sasaran Program',
            'Sasaran Kegiatan',
            'Program Dinas',
            'Kegiatan Dinas',
            'Sub Kegiatan',
            'Pengendalian Program',
            'Pengendalian Kegiatan',
            'Monitoring Kegiatan',
            'Monitoring Program',
            'Evaluasi Program',
            'Evaluasi Kegiatan',
            'Evaluasi Kinerja',
            'Evaluasi Pembangunan',
            'Pengendalian Pembangunan',
            'Pelaporan Kinerja',
            'Laporan Kinerja',
            'Laporan Tahunan',
            'Laporan Semester',
            'Laporan Triwulan',
            'Laporan Bulanan',
            'LKjIP',
            'SAKIP',
            'Capaian Kinerja',
            'Realisasi Kinerja',
            'Realisasi Program',
            'Realisasi Kegiatan',
            'Realisasi Anggaran',
            'DPA',
            'DPPA',
            'RKA',
            'RKPD',
            'KUA',
            'PPAS',
            'Renstra Perangkat Daerah',
            'Renja Perangkat Daerah',
            'Perubahan Renja',
            'Perubahan Anggaran',
            'Evaluasi Renja',
            'Evaluasi Renstra',
            'Data Perencanaan',
            'Data Kinerja',
            'Data Statistik',
            'Data Kebudayaan',
            'Data Program',
            'Data Kegiatan',
            'Data Indikator',
            'Dokumen Perencanaan',
            'Dokumen Evaluasi',
            'Dokumen Pelaporan',
            'Pengumpulan Data',
            'Pemutakhiran Data',
            'Sinkronisasi Data',
            'Verifikasi Data',
            'Validasi Data',

            /*
            |--------------------------------------------------------------------------
            | KEUANGAN
            |--------------------------------------------------------------------------
            */

            'Keuangan',
            'Administrasi Keuangan',
            'Pengelolaan Keuangan',
            'Anggaran',
            'Pagu Anggaran',
            'DPA Keuangan',
            'DPPA Keuangan',
            'RKA Keuangan',
            'Realisasi Anggaran',
            'Belanja Pegawai',
            'Belanja Barang',
            'Belanja Jasa',
            'Belanja Modal',
            'Belanja Perjalanan Dinas',
            'Belanja Hibah',
            'Belanja Operasional',
            'Pembayaran',
            'Tagihan',
            'SPJ',
            'SPJ Kegiatan',
            'SPJ Belanja',
            'SPJ Perjalanan Dinas',
            'SPJ Honorarium',
            'SPJ Pengadaan',
            'SPJ Operasional',
            'Pertanggungjawaban Keuangan',
            'Bukti Pengeluaran',
            'Kwitansi',
            'Nota Pembelian',
            'Faktur',
            'Pajak',
            'Pajak Daerah',
            'Pajak Pusat',
            'PPN',
            'PPh',
            'PPh 21',
            'PPh 22',
            'PPh 23',
            'PPh Final',
            'Setoran Pajak',
            'Bukti Setor',
            'Rekening Kegiatan',
            'Rekening Belanja',
            'Uang Persediaan',
            'UP',
            'GU',
            'TU',
            'LS',
            'Ganti Uang',
            'Tambahan Uang',
            'Pembayaran Langsung',
            'Laporan Keuangan',
            'Laporan Realisasi Anggaran',
            'LRA',
            'Rekonsiliasi Keuangan',
            'Rekonsiliasi Pajak',
            'Penatausahaan Keuangan',
            'Bendahara Pengeluaran',
            'Bendahara Penerimaan',
            'Buku Kas Umum',
            'BKUm',
            'Buku Pembantu',
            'Register Keuangan',
            'Verifikasi Keuangan',

            /*
            |--------------------------------------------------------------------------
            | KEGIATAN DINAS KEBUDAYAAN
            |--------------------------------------------------------------------------
            */

            'Kegiatan Kebudayaan',
            'Program Kebudayaan',
            'Pelestarian Kebudayaan',
            'Pengembangan Kebudayaan',
            'Perlindungan Kebudayaan',
            'Pemajuan Kebudayaan',
            'Seni dan Budaya',
            'Seni Tradisional',
            'Seni Pertunjukan',
            'Seni Rupa',
            'Seni Musik',
            'Seni Tari',
            'Seni Karawitan',
            'Tradisi',
            'Adat Istiadat',
            'Warisan Budaya',
            'Warisan Budaya Takbenda',
            'Cagar Budaya',
            'Pelestarian Cagar Budaya',
            'Museum',
            'Permuseuman',
            'Kepurbakalaan',
            'Arkeologi',
            'Dokumentasi Kebudayaan',
            'Pendataan Kebudayaan',
            'Kajian Kebudayaan',
            'Penelitian Kebudayaan',
            'Festival Budaya',
            'Pameran Kebudayaan',
            'Pagelaran Seni',
            'Pentas Seni',
            'Pertunjukan Budaya',
            'Lomba Seni',
            'Pembinaan Seni',
            'Pembinaan Seniman',
            'Komunitas Budaya',
            'Sanggar Seni',
            'Pelaku Budaya',
            'Seniman',
            'Budayawan',
            'Narasumber Kegiatan',
            'Kerja Sama Kebudayaan',
            'Kemitraan Kebudayaan',
            'Promosi Kebudayaan',
            'Publikasi Kebudayaan',
            'Dokumentasi Kegiatan',
            'Laporan Kegiatan',
            'Proposal Kegiatan',
            'Kerangka Acuan Kerja',
            'KAK',
            'TOR Kegiatan',
            'Jadwal Kegiatan',
            'Undangan Kegiatan',
            'Surat Tugas Kegiatan',
            'Surat Perintah Kegiatan',
            'Daftar Hadir Kegiatan',
            'Berita Acara Kegiatan',
            'Notulen Kegiatan',
            'Foto Kegiatan',
            'Video Kegiatan',
            'Materi Kegiatan',
            'Sertifikat Kegiatan',
            'Evaluasi Kegiatan Kebudayaan',
            'Pertanggungjawaban Kegiatan',
            'Hasil Kegiatan',
            'Capaian Kegiatan',
            'Rekomendasi Kegiatan',
            'Koordinasi Kegiatan',
            'Rapat Koordinasi',
            'Rapat Persiapan',
            'Rapat Evaluasi',
            'Kunjungan Kerja',
            'Perjalanan Dinas',
            'Pendampingan Kegiatan',
            'Monitoring Lapangan',
            'Verifikasi Lapangan',
            'Dokumen Kegiatan',
            'Arsip Kegiatan',
        ];

        $now = Carbon::now();

        $data = collect($tags)
            ->unique()
            ->map(function ($name) use ($now) {
                return [
                    'tag_uid' => (string) Str::uuid(),
                    'tag_name' => $name,
                    'tag_slug' => Str::slug($name),
                    'tag_description' => 'Tag arsip internal terkait ' . strtolower($name) . '.',
                    'tag_is_active' => true,
                    'tag_created_at' => $now,
                    'tag_updated_at' => null,
                ];
            })
            ->values()
            ->toArray();

        DB::table('sadarin_tag')->upsert($data, ['tag_name'], ['tag_description', 'tag_is_active', 'tag_updated_at']);
    }
}